### ISSUE TITLE
Add 'obsolete' to repository name

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/ccx-keys#4]
Since edX has forked this and is now maintaining it, I think it makes sense to change the repository name to `obsolete-ccx-keys` similar to what was done with sga. Just to reduce confusion. 

@cewing @cguardia @skleinfeldt

**Comment by cguardia** [comment]
Done.
carlos de la Guardia

```
  From: Peter Pinch <notifications@github.com>
```

 To: jazkarta/ccx-keys ccx-keys@noreply.github.com 
Cc: Carlos de la Guardia cguardia@yahoo.com
 Sent: Tuesday, February 23, 2016 9:46 AM
 Subject: [ccx-keys] Add 'obsolete' to repository name (#4)

Since edX has forked this and is now maintaining it, I think it makes sense to change the repository name to obsolete-ccx-keys similar to what was done with sga. Just to reduce confusion. @cewing @cguardia @skleinfeldt —
